### ISSUE TITLE
Data Capture: Implement a script for continuous measurement

### ISSUE THREAD

**Issue by bastianilso** [med-material/r-shiny-js-data-capture#6]
Our event-based data capture is implemented, which measures mouse clicks, mouse hover etc.
In addition, we will need to implement continuous measurements.

- The script measures mouse movement `mouseX`, `mouseY` on the screen in pixels.
- The script should take measurements at 60Hz (60 times per second).
- The script should log `Timestamp`, `SessionID`, Email (set to `anonymous` for now) and `Framecount` (if we can count frames from the web, otherwise, set this to `NA`).

The SessionID should be shared between continuous measurement and event-based measurements of course.

**Comment by bilal-62210** [comment]
@bastianilso It's ok for the script, the CSV file is like that : 
![image](https://user-images.githubusercontent.com/73820951/193803192-b615b3e2-0fdf-45c2-9b8e-84ad858435e2.png)
This is the Zip project if you want to show how it works before i push it on github:
[brush-whack.zip](https://github.com/med-material/r-shiny-js-data-capture/files/9705360/brush-whack.zip)
Give me your feedback
And i have a problem with the logging loader when i try to load this csv file, i have this message:
![image](https://user-images.githubusercontent.com/73820951/193804349-e6fda730-968d-49a3-a514-da9384456016.png)

**Comment by bilal-62210** [comment]
@bastianilso This is the lastest version : 
[brush-whack.zip](https://github.com/med-material/r-shiny-js-data-capture/files/9705868/brush-whack.zip)

**Comment by bilal-62210** [comment]
@bastianilso for the logging loader i don't understand the message because as you can see there is no problem for the logevent.csv, there is only a problem for the logcontinuousmeasurement.csv. I think the error it's on the Framecount column because it speak about 'NA'. But columuns "framecount" are the same for the 2 csv.
[log2022-10-4 13-24-9.251ContinuousMeasurement.csv](https://github.com/med-material/r-shiny-js-data-capture/files/9706331/log2022-10-4.13-24-9.251ContinuousMeasurement.csv)
[log2022-10-4 13-24-9.251Event.csv](https://github.com/med-material/r-shiny-js-data-capture/files/9706332/log2022-10-4.13-24-9.251Event.csv)

**Comment by bastianilso** [comment]
Hi bilal, the script must end with the name (timestamp) + `Sample.csv`, this is the assumed name. For example `log2022-10-4 13-24-9.251Sample.csv`.  In that case then `Sample` should not be passed as `NULL` to LoadFromDirectory.

`LoadFromDirectory("data/", meta=NULL)`


Alternatively a custom name must be passed to the LoadFromDirectory function.
`LoadFromDirectory("data/", sample="ContinuousMeasurement")`
In that case, your CSV file can be named `log2022-10-4 13-24-9.251ContinuousMeasurement.csv`.

Does it make sense? Otherwise drop by and I will show.

**Comment by bilal-62210** [comment]
@bastianilso Yes it's ok. I just tried and it works!
So if it's ok for you, i think we can close this issue.
